import React from 'react';
import YouTube from 'react-youtube'

export const textContent = {
    
    home: (
        <div>
            <center><YouTube videoId="libKVRa01L8"/></center>
            <p>The Solar System[a] is the gravitationally bound system of the Sun and the objects that orbit it, either directly or indirectly,[b] including the eight planets and five dwarf planets as defined by the International Astronomical Union (IAU). Of the objects that orbit the Sun directly, the largest eight are the planets,[c] with the remainder being smaller objects, such as dwarf planets and small Solar System bodies. Of the objects that orbit the Sun indirectly, the moons, two are larger than the smallest planet, Mercury.[d]</p>
            <p>The Solar System formed 4.6 billion years ago from the gravitational collapse of a giant interstellar molecular cloud. The vast majority of the system's mass is in the Sun, with the majority of the remaining mass contained in Jupiter. The four smaller inner planets, Mercury, Venus, Earth and Mars, are terrestrial planets, being primarily composed of rock and metal. The four outer planets are giant planets, being substantially more massive than the terrestrials. The two largest, Jupiter and Saturn, are gas giants, being composed mainly of hydrogen and helium; the two outermost planets, Uranus and Neptune, are ice giants, being composed mostly of substances with relatively high melting points compared with hydrogen and helium, called volatiles, such as water, ammonia and methane. All eight planets have almost circular orbits that lie within a nearly flat disc called the ecliptic.</p>
        </div>
    ),
    beginning: (
        <div>
            <center><YouTube videoId="HdPzOWlLrbE"/></center>
            <p>The earliest scientific models of the Universe were developed by ancient Greek and Indian philosophers and were geocentric, placing Earth at the centre of the Universe.[11][12] Over the centuries, more precise astronomical observations led Nicolaus Copernicus to develop the heliocentric model with the Sun at the centre of the Solar System. In developing the law of universal gravitation, Sir Isaac Newton built upon Copernicus' work as well as observations by Tycho Brahe and Johannes Kepler's laws of planetary motion.</p>
            <p>Further observational improvements led to the realization that our Sun is one of hundreds of billions of stars in a galaxy we call the Milky Way, which is one of at least hundreds of billions of galaxies in the Universe. Many of the stars in our galaxy have planets. At the largest scale galaxies are distributed uniformly and the same in all directions, meaning that the Universe has neither an edge nor a center. At smaller scales, galaxies are distributed in clusters and superclusters which form immense filaments and voids in space, creating a vast foam-like structure.[13] Discoveries in the early 20th century have suggested that the Universe had a beginning and that space has been expanding since then,[14] and is currently still expanding at an increasing rate.[15]</p>
            <p>The Big Bang theory is the prevailing cosmological description of the development of the Universe. Under this theory, space and time emerged together 13.799±0.021 billion years ago[2] with a fixed amount of energy and matter that has become less dense as the Universe has expanded. After an initial accelerated expansion at around 10−32 seconds, and the separation of the four known fundamental forces, the Universe gradually cooled and continued to expand, allowing the first subatomic particles and simple atoms to form. Dark matter gradually gathered forming a foam-like structure of filaments and voids under the influence of gravity. Giant clouds of hydrogen and helium were gradually drawn to the places where dark matter was most dense, forming the first galaxies, stars, and everything else seen today. It is possible to see objects that are now further away than 13.799 billion light-years because space itself has expanded, and it is still expanding today. This means that objects which are now up to 46 billion light years away can still be seen in their distant past, because in the past when their light was emitted, they were much closer to us.</p>
            <p>From studying the movement of galaxies, we know that the universe contains much more matter than we can detect in usual ways. This unseen matter is known as dark matter [16] (dark means that there is a wide range of strong indirect evidence that it exists, but we have not yet detected it directly). The Lambda-CDM model is the most widely accepted model of our universe. It suggests that about 69.2%±1.2% [2015] of the mass and energy in the universe is a scalar field known as dark energy which is responsible for the current expansion of space, and about 25.8% [2015] is dark matter.[17] Ordinary ("baryonic") matter is therefore only 4.9% [2015] of the physical universe.[17] Stars, planets, and visible gas clouds only form about 6% of ordinary matter, or about 0.3% of the entire universe.[18]</p>
            <p>There are many competing hypotheses about the ultimate fate of the universe and about what, if anything, preceded the Big Bang, while other physicists and philosophers refuse to speculate, doubting that information about prior states will ever be accessible. Some physicists have suggested various multiverse hypotheses, in which the Universe might be one among many universes that likewise exist.[3][19][20]"</p>
        </div>
    ),
    formation1: (
        <div>
            <center><YouTube videoId="x1QTc5YeO6w"/></center>
            <p>The formation and evolution of the Solar System began 4.6 billion years ago with the gravitational collapse of a small part of a giant molecular cloud.[1] Most of the collapsing mass collected in the center, forming the Sun, while the rest flattened into a protoplanetary disk out of which the planets, moons, asteroids, and other small Solar System bodies formed.</p>
            <p>This model, known as the nebular hypothesis was first developed in the 18th century by Emanuel Swedenborg, Immanuel Kant, and Pierre-Simon Laplace. Its subsequent development has interwoven a variety of scientific disciplines including astronomy, physics, geology, and planetary science. Since the dawn of the space age in the 1950s and the discovery of extrasolar planets in the 1990's, the model has been both challenged and refined to account for new observations.</p>
            <p>The Solar System has evolved considerably since its initial formation. Many moons have formed from circling discs of gas and dust around their parent planets, while other moons are thought to have formed independently and later been captured by their planets. Still others, such as Earth's Moon, may be the result of giant collisions. Collisions between bodies have occurred continually up to the present day and have been central to the evolution of the Solar System. The positions of the planets might have shifted due to gravitational interactions.[2] This planetary migration is now thought to have been responsible for much of the Solar System's early evolution.</p>
            <p>In roughly 5 billion years, the Sun will cool and expand outward to many times its current diameter (becoming a red giant), before casting off its outer layers as a planetary nebula and leaving behind a stellar remnant known as a white dwarf. In the far distant future, the gravity of passing stars will gradually reduce the Sun's retinue of planets. Some planets will be destroyed, others ejected into interstellar space. Ultimately, over the course of tens of billions of years, it is likely that the Sun will be left with none of the original bodies in orbit around it.[3]</p>
        </div>
    ),
    formation2: (
        <div>
            <p>The standard model for the formation of the Solar System (including the Earth) is the solar nebula hypothesis.[23] In this model, the Solar System formed from a large, rotating cloud of interstellar dust and gas called the solar nebula. It was composed of hydrogen and helium created shortly after the Big Bang 13.8 Ga (billion years ago) and heavier elements ejected by supernovae. About 4.5 Ga, the nebula began a contraction that may have been triggered by the shock wave from a nearby supernova.[24] A shock wave would have also made the nebula rotate. As the cloud began to accelerate, its angular momentum, gravity, and inertia flattened it into a protoplanetary disk perpendicular to its axis of rotation. Small perturbations due to collisions and the angular momentum of other large debris created the means by which kilometer-sized protoplanets began to form, orbiting the nebular center.[25]</p>
            <p>The center of the nebula, not having much angular momentum, collapsed rapidly, the compression heating it until nuclear fusion of hydrogen into helium began. After more contraction, a T Tauri star ignited and evolved into the Sun. Meanwhile, in the outer part of the nebula gravity caused matter to condense around density perturbations and dust particles, and the rest of the protoplanetary disk began separating into rings. In a process known as runaway accretion, successively larger fragments of dust and debris clumped together to form planets.[25] Earth formed in this manner about 4.54 billion years ago (with an uncertainty of 1%)[26][27][4][28] and was largely completed within 10–20 million years.[29] The solar wind of the newly formed T Tauri star cleared out most of the material in the disk that had not already condensed into larger bodies. The same process is expected to produce accretion disks around virtually all newly forming stars in the universe, some of which yield planets.[30]</p>
            <p>The proto-Earth grew by accretion until its interior was hot enough to melt the heavy, siderophile metals. Having higher densities than the silicates, these metals sank. This so-called iron catastrophe resulted in the separation of a primitive mantle and a (metallic) core only 10 million years after the Earth began to form, producing the layered structure of Earth and setting up the formation of Earth's magnetic field.[31] J. A. Jacobs [32] was the first to suggest that the inner core—a solid center distinct from the liquid outer core—is freezing and growing out of the liquid outer core due to the gradual cooling of Earth's interior (about 100 degrees Celsius per billion years[33]). </p>
            <p>The first eon in Earth's history, the Hadean, begins with the Earth's formation and is followed by the Archean eon at 3.8 Ga.[2]:145 The oldest rocks found on Earth date to about 4.0 Ga, and the oldest detrital zircon crystals in rocks to about 4.4 Ga,[34][35][36] soon after the formation of the Earth's crust and the Earth itself. The giant impact hypothesis for the Moon's formation states that shortly after formation of an initial crust, the proto-Earth was impacted by a smaller protoplanet, which ejected part of the mantle and crust into space and created the Moon.[37][38][39]</p>
            <p>From crater counts on other celestial bodies, it is inferred that a period of intense meteorite impacts, called the Late Heavy Bombardment, began about 4.1 Ga, and concluded around 3.8 Ga, at the end of the Hadean.[40] In addition, volcanism was severe due to the large heat flow and geothermal gradient.[41] Nevertheless, detrital zircon crystals dated to 4.4 Ga show evidence of having undergone contact with liquid water, suggesting that the Earth already had oceans or seas at that time.[34]</p>
            <p>By the beginning of the Archean, the Earth had cooled significantly. Present life forms could not have survived at Earth's surface, because the Archean atmosphere lacked oxygen hence had no ozone layer to block ultraviolet light. Nevertheless, it is believed that primordial life began to evolve by the early Archean, with candidate fossils dated to around 3.5 Ga.[42] Some scientists even speculate that life could have begun during the early Hadean, as far back as 4.4 Ga, surviving the possible Late Heavy Bombardment period in hydrothermal vents below the Earth's surface.[43] </p>
            <p>Earth's only natural satellite, the Moon, is larger relative to its planet than any other satellite in the solar system.[nb 1] During the Apollo program, rocks from the Moon's surface were brought to Earth. Radiometric dating of these rocks shows that the Moon is 4.53 ± 0.01 billion years old,[46] formed at least 30 million years after the solar system.[47] New evidence suggests the Moon formed even later, 4.48 ± 0.02 Ga, or 70–110 million years after the start of the Solar System.[48]</p>
            <p>Theories for the formation of the Moon must explain its late formation as well as the following facts. First, the Moon has a low density (3.3 times that of water, compared to 5.5 for the earth[49]) and a small metallic core. Second, there is virtually no water or other volatiles on the moon. Third, the Earth and Moon have the same oxygen isotopic signature (relative abundance of the oxygen isotopes). Of the theories proposed to account for these phenomena, one is widely accepted: The giant impact hypothesis proposes that the Moon originated after a body the size of Mars (sometimes named Theia[47]) struck the proto-Earth a glancing blow.[1]:256[50][51]</p>
            <p>The collision released about 100 million times more energy than the more recent Chicxulub impact that is believed to have caused the extinction of the dinosaurs. It was enough to vaporize some of the Earth's outer layers and melt both bodies.[50][1]:256 A portion of the mantle material was ejected into orbit around the Earth. The giant impact hypothesis predicts that the Moon was depleted of metallic material,[52] explaining its abnormal composition.[53] The ejecta in orbit around the Earth could have condensed into a single body within a couple of weeks. Under the influence of its own gravity, the ejected material became a more spherical body: the Moon.[54]</p>
        </div>
    ),
    sun: (
        <div>
            <center><YouTube videoId="2HoTK_Gqi2Q"/></center>
            <p>The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma,[14][15] with internal convective motion that generates a magnetic field via a dynamo process.[16] It is by far the most important source of energy for life on Earth. Its diameter is about 1.39 million kilometers, i.e. 109 times that of Earth, and its mass is about 330,000 times that of Earth, accounting for about 99.86% of the total mass of the Solar System.[17] About three quarters of the Sun's mass consists of hydrogen (~73%); the rest is mostly helium (~25%), with much smaller quantities of heavier elements, including oxygen, carbon, neon, and iron.[18]</p>
            <p>The Sun is a G-type main-sequence star (G2V) based on its spectral class. As such, it is informally and not completely accurately referred to as a yellow dwarf (its light is closer to white than yellow). It formed approximately 4.6 billion[a][10][19] years ago from the gravitational collapse of matter within a region of a large molecular cloud. Most of this matter gathered in the center, whereas the rest flattened into an orbiting disk that became the Solar System. The central mass became so hot and dense that it eventually initiated nuclear fusion in its core. It is thought that almost all stars form by this process.</p>
            <p>The Sun is roughly middle-aged; it has not changed dramatically for more than four billion[a] years, and will remain fairly stable for more than another five billion years. It currently fuses about 600 million tons of hydrogen into helium every second, converting 4 million tons of matter into energy every second as a result. This energy, which can take between 10,000 and 170,000 years to escape from its core, is the source of the Sun's light and heat. In about 5 billion years, when hydrogen fusion in its core has diminished to the point at which the Sun is no longer in hydrostatic equilibrium, the core of the Sun will experience a marked increase in density and temperature while its outer layers expand to eventually become a red giant. It is calculated that the Sun will become sufficiently large to engulf the current orbits of Mercury and Venus, and render Earth uninhabitable. After this, it will shed its outer layers and become a dense type of cooling star known as a white dwarf, which no longer produces energy by fusion, but still glows and gives off heat from its previous fusion.</p>
            <p>The enormous effect of the Sun on Earth has been recognized since prehistoric times, and the Sun has been regarded by some cultures as a deity. The synodic rotation of Earth and its orbit around the Sun are the basis of solar calendars, one of which is the predominant calendar in use today.</p>
        </div>
    ),
}